version: "3"
services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
        - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/izeaapp
    ports:
      - "3000:3000"
    depends_on:
      - db

